[versions]
jooq = "3.21.8"
postgresql = "42.7.13"
swagger-annotations = "2.2.25"
jakarta-annotation-api = "3.0.0"

[libraries]
# JOOQ
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
jooq-codegen = { module = "org.jooq:jooq-codegen", version.ref = "jooq" }
jooq-meta = { module = "org.jooq:jooq-meta", version.ref = "jooq" }

# Database
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

# Annotations
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations", version.ref = "swagger-annotations" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation-api" }
